ignores:
  # commitlint packages are used by husky, but not detected
  - "@commitlint/cli"
  - "@commitlint/config-conventional"
  # Used in getChannels.ts to access types used by @slack/bolt
  # Don't want to list it explicitly to avoid version mismatch issues
  - "@slack/web-api"
  # Used internally by slack-bolt-sequelize (prod)
  - "pg"
  # Provided by slack-bolt-sequelize; type errors can occur if we try to bring our own
  - "sequelize"
  # Used internally by slack-bolt-sequelize (dev)
  - "sqlite3"
